---
title: "Method Comparison"
author: "Bahar"
date: "`r Sys.Date()`"
output: html_document
---

Assessing aggreement between `r input$var1` and `r input$var2` measuments by means of Bland-Altman plot.

```{r BA plot, echo=FALSE}
library(mcr)
a <- datasetInput()[,c(input$var1,input$var2), drop=FALSE]
    if (is.null(a)) {
      return(NULL)} else {
        names(a) <- c("M1", "M2")
        data1 <- mcreg(a$M1,a$M2,
                      mref.name=input$var1,mtest.name=input$var2)
        MCResult.plotDifference(data1, plot.type=input$batype, add.grid = TRUE)
      }
```

Comparison of `r input$var1` and `r input$var2` measurements using regression analysis.

```{r regression plot, echo=FALSE}
library(mcr)
a <- datasetInput()[,c(input$var1,input$var2), drop=FALSE]
    if (is.null(a)) {
      return(NULL)} else {
        names(a) <- c("M1", "M2")
        data1<- mcreg(a$M1,a$M2, error.ratio = input$syx, 
                      method.reg = input$regmodel, method.ci = input$cimethod,
                      method.bootstrap.ci = input$metbootci)
        MCResult.plot(data1, ci.area=input$ciarea, 
             add.legend=input$legend, identity=input$identity,
             add.cor=input$addcor, x.lab=input$var1,
             y.lab=input$var2, cor.method=input$cormet, 
             equal.axis = TRUE, add.grid = TRUE)
      }
```

```{r statistics, echo=FALSE}
library(mcr)
a <- datasetInput()[,c(input$var1,input$var2), drop=FALSE]
    if (is.null(a)) {
      return(NULL)} else {
        names(a) <- c("M1", "M2")
        data1 <- mcreg(a$M1,a$M2, error.ratio=input$syx, 
                      method.reg=input$regmodel, method.ci=input$cimethod,
                      method.bootstrap.ci = input$metbootci,
                      mref.name = input$var1, mtest.name = input$var2)
        printSummary(data1)
      }
```

Data is processed using `r R.version.string` and mcr package `r packageVersion('mcr')`.
