library(shiny)
library(mcr)
shinyUI(fluidPage(
  titlePanel("Method Comparison"),
  sidebarLayout(
    sidebarPanel(
      fileInput('file1', 'Choose CSV File',
                accept=c('text/csv', 
                         'text/comma-separated-values,text/plain', 
                         '.csv')),
#      tags$hr(),
      checkboxInput('header', 'Header', TRUE),
      radioButtons('sep', 'Data Separator',
                   c(Comma=',',
                     Semicolon=';',
                     Tab='\t'),
                   ','),
      radioButtons('quote', 'Quote',
                   c(None='',
                     'Double Quote'='"',
                     'Single Quote'="'"),
                   '"'),
#      tags$hr(),
      selectInput('batype', 'Bland-Altman Plot Type', 
                  choices=list('0.5*(X+Y) vs. Y-X'=3,
                              'X vs. Y-X'=1,
                              'X vs. (Y-X)/X'=2,
                              '0.5*(X+Y) vs. (Y-X)/X'=4,
                              'rank(X) vs. Y-X'=5,
                              'rank(X) vs. (Y-X)/X'=6,
                              'sqrt(X*Y) vs. Y/X'=7,
                              '0.5*(X+Y) vs. (Y-X) / (0.5*(X+Y))'=8)),
#      tags$hr(),
      selectInput('regmodel', 'Regression Model', 
                  choices=list('Ordinary Least Square'='LinReg',
                               'Weighted Ordinary Least Square'='WLinReg',
                               'Deming'='Deming',
                               'Weighted Deming'='WDeming',
                               'Passing-Bablok'='PaBa',
                               'Passing-Bablok Large Data'='PaBaLarge')),
#      tags$hr(),
      selectInput('cimethod', 'CI Method', 
                  choices=list('Analytical'='analytical',
                               'Jacknife'='jackknife',
                               'Bootstrap'='bootstrap',
                               'Nested Bootstrap'='nestedbootstrap')),
#      tags$hr(),
      numericInput('syx', 'Sy/Sx', value=1),
      checkboxInput('identity', 'Add identity line',value=TRUE),
      checkboxInput('ciarea', 'Add CI Area',value=TRUE),
      checkboxInput('legend', 'Add Legend',value=TRUE),
      checkboxInput('addcor', 'Add Correlation',value=TRUE),
#      tags$hr(),
      radioButtons('format', 'Document format', c('PDF', 'HTML', 'Word'),
                   inline = TRUE),
      downloadButton('downloadReport')
    ),
    mainPanel(
      tabsetPanel(type = "tabs", 
                  tabPanel("Bland-Altman", plotOutput("plot1")),
                  tabPanel("Regression", plotOutput("plot2")),
                  tabPanel("Statistics", verbatimTextOutput("summary")), 
                  tabPanel("Data", tableOutput("table"))
      )
    )
  )
))